<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_remoteimage
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/modeladmin.php' ;

/**
 * Remoteimage model.
 */
class RemoteimageModelManager extends JModelLegacy
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_REMOTEIMAGE';
	
	public 		$component = 'remoteimage' ;
	public 		$item_name = 'manager' ;
	public 		$list_name = 'managers' ;
	
	
	/*
	 * function __construct
	 * @param 
	 */
	
	public function __construct($config = array())
	{		
		parent::__construct($config) ;
	}
	
}