<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_remoteimage
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/modeladmin.php' ;

/**
 * Remoteimage model.
 */
class RemoteimageModelManager extends JModelLegacy
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_REMOTEIMAGE';
	
	public 		$component = 'remoteimage' ;
	public 		$item_name = 'manager' ;
	public 		$list_name = 'managers' ;
	
	
	/*
	 * function get_children
	 * @param 
	 */
	
	public function get_children()
	{
		//$ftp 	= RMHelper::getFTP();
		$params = JComponentHelper::getParams('com_remoteimage') ;
		$path 	= JRequest::getVar('path', $params->get('Ftp_Path')) ;
		
		$ftp = RMHelper::getFTP();
		
		$details = $ftp->listDetails($path, 'folders');
		
		$return = array();
		
		foreach( $details as $detail ):
			$tmp = new JObject();
			
			
			$tmp->attr = new JObject();
			$tmp->attr->path = $path . '/' . $detail['name'] ;
			$tmp->attr->rel = 'folder' ;
			
			$tmp->data = $detail['name'] ;
			$tmp->state = 'closed' ;
			
			$return[] = $tmp ;
		endforeach;
		
		
		return $return;
	}
	
	
}