<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_remoteimage
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$view = JRequest::getVar('view') ;
JRequest::setVar('view'		, 'api', 'method', true) ;
JRequest::setVar('format'	, 'json', 'method', true) ;

JFactory::$document = JDocument::getInstance('json') ;

include_once dirname(__FILE__).'/controllerapi.php' ;
include_once dirname(__FILE__).'/viewapi.php' ;
include_once dirname(__FILE__).'/errorapi.php' ;

ApiError::attachHandler();