<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_remoteimage
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');
JHtml::_('behavior.keepalive');
RemoteimageHelper::_('include.core');
JHtml::_('jquery.framework', true);
RMHelper::_('include.addJS', 'jstree/_lib/jquery.cookie.js');
RMHelper::_('include.addJS', 'jstree/_lib/jquery.hotkeys.js');
RMHelper::_('include.addJS', 'jstree/jquery.jstree.js');
RMHelper::_('include.addJS', 'folder-tree.js');


$app = JFactory::getApplication() ;
if( JVERSION >= 3){
	JHtml::_('formbehavior.chosen', 'select');
	if($app->isSite()){
		//RemoteimageHelper::_('include.fixBootstrapToJoomla');
	}
}else{
	RemoteimageHelper::_('include.bluestork');
	// RemoteimageHelper::_('include.fixBootstrapToJoomla');
}



// Init some API objects
// ================================================================================
$date 	= JFactory::getDate( 'now' , JFactory::getConfig()->get('offset') ) ;
$doc 	= JFactory::getDocument() ;
$uri 	= JFactory::getURI() ;
$user	= JFactory::getUser() ;



// For Site
// ================================================================================
if($app->isSite()) {
	RemoteimageHelper::_('include.isis');
}



// Edit setting
// ================================================================================
$tabs 	= count( $this->fields ) > 1 ? true : false;


if($app->isAdmin()) {
	$span_left 	= 8 ;
	$span_right = 4 ;
	
	$width_left = 60 ;
	$width_right= 40 ;
}else{
	$span_left 	= 12 ;
	$span_right = 12 ;
	
	$width_left = 100 ;
	$width_right= 100 ;
}

?>
<script type="text/javascript">
	<?php if( $app->isSite() ): ?>
	WindWalker.fixToolbar(0, 300) ;
	<?php endif; ?>
	
	Joomla.submitbutton = function(task)
	{
		if (task == 'manager.cancel' || document.formvalidator.isValid(document.id('manager-form'))) {
			Joomla.submitform(task, document.getElementById('manager-form'));
		}
		else {
			alert('<?php echo $this->escape(JText::_('JGLOBAL_VALIDATION_FORM_FAILED'));?>');
		}
	}
</script>

<div id="remoteimage-manager-edit" class="<?php echo (JVERSION >= 3) ? 'joomla30' : 'joomla25' ?>">

	<form action="<?php echo JRoute::_( JFactory::getURI()->toString() ); ?>" method="post" name="adminForm" id="manager-form" class="form-validate" enctype="multipart/form-data">	
		
		<!-- Bodys -->
		<div class="row-fluid">
			<div id="remote-folder" class="<?php echo ( JVERSION >= 3 ) ? 'span3' : 'width-30 fltlft' ?>">
				<div id="remote-folder-wrap">
					<ul>
						<li id="phtml_1">
							<a href="#">A</a>
						</li>
						<li>
							<a href="#">B</a>
						</li>
						<li>
							<a href="#">C</a>
						</li>
					</ul>
				</div>
			</div>
			
			
			<div id="remote-images" class="<?php echo ( JVERSION >= 3 ) ? 'span9' : 'width-70 fltlft' ?>">
				3212
			</div>
		</div>
		
		
		
		<!-- Hidden Inputs -->
		<div id="hidden-inputs">
			<input type="hidden" name="option" value="com_remoteimage" />
			<input type="hidden" name="task" value="" />
			<?php echo JHtml::_('form.token'); ?>
		</div>
		<div class="clr"></div>
	</form>

</div>