<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_remoteimage
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;


// Init some API objects
// ================================================================================
$date 	= JFactory::getDate( 'now' , JFactory::getConfig()->get('offset') ) ;
$doc 	= JFactory::getDocument() ;
$uri 	= JFactory::getURI() ;
$user	= JFactory::getUser() ;
$app 	= JFactory::getApplication() ;
$lang	= JFactory::getLanguage();
$lang_code = $lang->getTag();
$lang_code = str_replace('-', '_', $lang_code) ;


// Include elFinder and JS
// ================================================================================
JHtml::_('behavior.framework', true);

if( JVERSION >= 3){
	
	// jQuery
	JHtml::_('jquery.framework', true);
	JHtml::_('bootstrap.framework', true);

}else{
	if($this->modal){
		$doc->addStyleSheet('components/com_remoteimage/includes/bootstrap/css/bootstrap.min.css');
	}
	
	// jQuery
	$doc->addScript( 'components/com_remoteimage/includes/js/jquery/jquery.js' );
	$doc->addScriptDeclaration('jQuery.noConflict();');
}


// elFinder includes
$doc->addStylesheet( 'components/com_remoteimage/includes/js/jquery-ui/css/smoothness/jquery-ui-1.8.24.custom.css' );
$doc->addStylesheet( 'components/com_remoteimage/includes/js/elfinder/css/elfinder.min.css' );
$doc->addStylesheet( 'components/com_remoteimage/includes/js/elfinder/css/theme.css' );

$doc->addscript( 'components/com_remoteimage/includes/js/jquery-ui/js/jquery-ui-1.8.24.custom.min.js' );
$doc->addscript( 'components/com_remoteimage/includes/js/elfinder/js/elfinder.min.js' );
JHtml::script( JURI::base().'components/com_remoteimage/includes/js/elfinder/js/i18n/elfinder.'.$lang_code.'.js' );
RMHelper::_('include.core');



// For Site
// ================================================================================
if($app->isSite()) {
	RemoteimageHelper::_('include.isis');
}



?>
<script type="text/javascript">
	var elFinder
	var elSelected ;
	var el ;
	var RMinModal ;
	
	// Insert Image to Article
	var insertImageToParent = function(){
		var imgs 	= elSelected ;
		
		if( elSelected.length < 1 ) {
			return ;
		}
		
		var fixAll	= $('rm-setwidth').checked ;
		var dW 		= $('rm-width').get('value').toInt() ;
		var options = {
			fixAll : fixAll,
			dW : dW
		}
		//var dH 		= $('rm-height').get('value').toInt() ;
		
		
		if (window.parent) window.parent.insertImage(imgs, window.elFinder, options);
	}
	
	
	// Init elFinder
	jQuery(document).ready(function($) {
		elFinder = $('#elfinder').elfinder({
			url : 'index.php?option=com_remoteimage&task=manager' ,
			width : '100%' ,
			lang : '<?php echo $lang_code; ?>',
			handlers : {
				select : function(event, elfinderInstance) {
					var selected = event.data.selected;
	
					if (selected.length) {
						elSelected = [];
						jQuery.each(selected, function(i, e){
							elSelected[i] = elfinderInstance.file(e);
						});
					}
	
				}
			}
			<?php if( $this->modal ): ?>
			,
			getFileCallback : function(file){
				insertImageToParent();
			}
			
			<?php endif; ?>
			
		}).elfinder('instance');
	});
</script>

<div id="remoteimage-manager" class="<?php echo (JVERSION >= 3) ? 'joomla30' : 'joomla25' ?>">
		
		<div class="system-info">
			<?php
			$upload_max = ini_get('upload_max_filesize') ;
			$upload_num = ini_get('max_file_uploads') ;
			?>
			
			<?php echo JText::_('COM_REMOTEIMAGE_UPLOAD_MAX'); ?> <?php echo $upload_max; ?>
			|
			<?php echo JText::_('COM_REMOTEIMAGE_UPLOAD_NUM'); ?> <?php echo $upload_num; ?>
			
		</div>
		
		<!-- Bodys -->
		<div class="row-fluid">
			<div id="elfinder" class="span12 rm-finder">
				
			</div>
		</div>
		
		
		<?php if( $this->modal || AKDEBUG ): ?>
		<div class="row-fluid">
			<div id="rm-insert-panel" class="span12 form-actions">
				<div class="form-inline pull-left">
					<label for="rm-width" id="rm-width-lbl" class=""><?php echo JText::_('COM_REMOTEIMAGE_MAX_WIDTH'); ?></label>
					<input type="text" id="rm-width" class="input input-mini" value="<?php echo $this->params->get('Image_DefaultWidth_Midium', 640); ?>" />
					&nbsp;&nbsp;
					<!--<span class="rm-width-height-x">X</span>
					<input type="text" id="rm-height" class="input input-mini" value="<?php echo $this->params->get('Image_DefaultHeight_Midium', 640); ?>" />
					-->
					<label for="rm-setwidth">
						<input type="checkbox" id="rm-setwidth" name="rm-setwidth" value="1" />
						<?php echo JText::_('COM_REMOTEIMAGE_FIX_ALL_IMAGE_WIDTH'); ?>
					</label>
						
				</div>
				
				
				<div class="btns pull-right fltrt">
					
					<button id="rm-insert-button" class="btn btn-primary" onclick="window.insertImageToParent();">
						<?php echo JText::_('COM_REMOTEIMAGE_INSERT_IMAGES'); ?>
					</button>
					
					<button id="rm-cancel-button" class="btn" onclick="window.parent.SqueezeBox.close();">
						<?php echo JText::_('JLIB_HTML_BEHAVIOR_CLOSE'); ?>
					</button>
					
				</div>
			</div>
		</div>
		<?php endif; ?>

</div>