<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_remoteimage
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;


include_once AKPATH_COMPONENT.'/controllerform.php' ;

/**
 * Manager controller class.
 */
class RemoteimageControllerManager extends AKControllerForm
{
	
	public $view_list = 'managers' ;
	public $view_item = 'manager' ;
	public $component = 'remoteimage';

	
	/**
     * Constructor.
     *
     * @param   array  $config  An optional associative array of configuration settings.
     *
     * @see     JController
     * @since   11.1
     */
	
    function __construct() {
		
		$this->allow_url_params = array(
			'return'
		);
		
		$this->redirect_tasks = array(
			'save', 'cancel', 'publish', 'unpublish', 'delete'
		);
		
        parent::__construct();
    }
	
	
	
	/*
	 * function server
	 * @param 
	 */
	
	public function server()
	{
		$model = $this->getModel();
		$operation = JRequest::getVar('operation', 'get_children') ;
		$result = $model->$operation() ;
		
		echo json_encode($result);
		
		jexit();
	}

	
	
	/**
     * Function that allows child controller access to model data
     * after the data has been saved.
     *
     * @param   JModel  &$model     The data model object.
     * @param   array   $validData  The validated data.
     *
     * @return  void 
     *
     * @since   11.1
     */
	
	protected function postSaveHook( &$model, $validData = array())
    {
		$result = $model->postSaveHook($validData) ;
		return $result ;
    }
	
}